# Generated by Django 3.2.5 on 2022-08-16 09:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0003_rename_address_address_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='address',
        ),
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.OneToOneField(blank=-1, null=True, on_delete=django.db.models.deletion.CASCADE, to='mainApp.address'),
        ),
    ]
