# Generated by Django 3.2.5 on 2022-08-20 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0007_user_password2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password2',
            field=models.CharField(max_length=30),
        ),
    ]
