# Generated by Django 3.2.5 on 2022-09-03 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0012_subcategory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subcategory',
            options={'managed': True, 'verbose_name_plural': 'SubCategory'},
        ),
    ]
