# Generated by Django 3.2.5 on 2022-09-04 04:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0016_category_parent_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='product_subcategory',
        ),
        migrations.DeleteModel(
            name='SubCategory',
        ),
    ]
