# Generated by Django 3.2.5 on 2022-12-02 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0018_user_mobile_count'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='mobile_count',
            new_name='otp_counter',
        ),
    ]
