# Generated by Django 3.2.5 on 2022-12-05 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0019_rename_mobile_count_user_otp_counter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='lat',
        ),
        migrations.RemoveField(
            model_name='address',
            name='lon',
        ),
    ]
