# Generated by Django 3.2.5 on 2023-01-10 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0026_auto_20230110_0831'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='product_description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='product_image',
            new_name='image',
        ),
    ]
